// 错误码定义
// 命名规范: "模块_错误描述"

export const ERROR_CODES = {
  // 认证错误 (AUTH_)
  AUTH: {
    WALLET_REJECTED: 'AUTH_WALLET_REJECTED',
    WALLET_NOT_FOUND: 'AUTH_WALLET_NOT_FOUND',
    SIGN_FAILED: 'AUTH_SIGN_FAILED',
    ENS_RESOLVE_FAILED: 'AUTH_ENS_RESOLVE_FAILED',
    INVALID_MESSAGE: 'AUTH_INVALID_MESSAGE',
    NOT_CONNECTED: 'AUTH_NOT_CONNECTED',
  },

  // 邮件错误 (EMAIL_)
  EMAIL: {
    IMAP_AUTH_FAILED: 'EMAIL_IMAP_AUTH_FAILED',
    SMTP_AUTH_FAILED: 'EMAIL_SMTP_AUTH_FAILED',
    SEND_FAILED: 'EMAIL_SEND_FAILED',
    SYNC_TIMEOUT: 'EMAIL_SYNC_TIMEOUT',
    RATE_LIMITED: 'EMAIL_RATE_LIMITED',
    INVALID_RECIPIENT: 'EMAIL_INVALID_RECIPIENT',
    ACCOUNT_NOT_FOUND: 'EMAIL_ACCOUNT_NOT_FOUND',
    FOLDER_NOT_FOUND: 'EMAIL_FOLDER_NOT_FOUND',
  },

  // AI 错误 (AI_)
  AI: {
    PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
    API_KEY_INVALID: 'AI_API_KEY_INVALID',
    RATE_LIMITED: 'AI_RATE_LIMITED',
    CONTEXT_TOO_LONG: 'AI_CONTEXT_TOO_LONG',
    LOCAL_MODEL_NOT_FOUND: 'AI_LOCAL_MODEL_NOT_FOUND',
    GENERATION_FAILED: 'AI_GENERATION_FAILED',
  },

  // 标签错误 (TAG_)
  TAG: {
    DUPLICATE_NAME: 'TAG_DUPLICATE_NAME',
    NOT_FOUND: 'TAG_NOT_FOUND',
    CLASSIFY_FAILED: 'TAG_CLASSIFY_FAILED',
  },

  // 网络错误 (NET_)
  NETWORK: {
    OFFLINE: 'NET_OFFLINE',
    TIMEOUT: 'NET_TIMEOUT',
    DNS_FAILED: 'NET_DNS_FAILED',
  },

  // 数据库错误 (DB_)
  DATABASE: {
    MIGRATION_FAILED: 'DB_MIGRATION_FAILED',
    CORRUPT: 'DB_CORRUPT',
    WRITE_FAILED: 'DB_WRITE_FAILED',
    READ_FAILED: 'DB_READ_FAILED',
  },

  // 聊天错误 (CHAT_)
  CHAT: {
    INIT_FAILED: 'CHAT_INIT_FAILED',
    SEND_FAILED: 'CHAT_SEND_FAILED',
    GET_MESSAGES_FAILED: 'CHAT_GET_MESSAGES_FAILED',
    GET_CONVERSATIONS_FAILED: 'CHAT_GET_CONVERSATIONS_FAILED',
    PEER_NOT_FOUND: 'CHAT_PEER_NOT_FOUND',
    ENCRYPT_FAILED: 'CHAT_ENCRYPT_FAILED',
  },

  // 通用错误
  COMMON: {
    INVALID_PARAMS: 'INVALID_PARAMS',
    NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
    UNKNOWN: 'UNKNOWN_ERROR',
  },
} as const

export type ErrorCodeType = typeof ERROR_CODES

// 错误消息映射
export const ERROR_MESSAGES: Record<string, string> = {
  [ERROR_CODES.AUTH.WALLET_REJECTED]: '用户拒绝了钱包连接',
  [ERROR_CODES.AUTH.WALLET_NOT_FOUND]: '未检测到钱包扩展，请安装 MetaMask 或其他钱包',
  [ERROR_CODES.AUTH.SIGN_FAILED]: '签名失败，请重试',
  [ERROR_CODES.AUTH.ENS_RESOLVE_FAILED]: 'ENS 域名解析失败',
  [ERROR_CODES.AUTH.NOT_CONNECTED]: '钱包未连接',

  [ERROR_CODES.EMAIL.IMAP_AUTH_FAILED]: 'IMAP 认证失败，请检查邮箱设置',
  [ERROR_CODES.EMAIL.SMTP_AUTH_FAILED]: 'SMTP 认证失败，请检查邮箱设置',
  [ERROR_CODES.EMAIL.SEND_FAILED]: '邮件发送失败',
  [ERROR_CODES.EMAIL.SYNC_TIMEOUT]: '邮件同步超时，请稍后重试',
  [ERROR_CODES.EMAIL.RATE_LIMITED]: '请求过于频繁，请稍后再试',
  [ERROR_CODES.EMAIL.INVALID_RECIPIENT]: '收件人地址无效',
  [ERROR_CODES.EMAIL.ACCOUNT_NOT_FOUND]: '邮箱账户不存在',

  [ERROR_CODES.AI.PROVIDER_UNAVAILABLE]: 'AI 服务商暂时不可用',
  [ERROR_CODES.AI.API_KEY_INVALID]: 'API Key 无效',
  [ERROR_CODES.AI.RATE_LIMITED]: 'AI 调用频率超限',
  [ERROR_CODES.AI.LOCAL_MODEL_NOT_FOUND]: '本地 LLM 模型未安装',

  [ERROR_CODES.NETWORK.OFFLINE]: '网络连接已断开',
  [ERROR_CODES.NETWORK.TIMEOUT]: '请求超时',

  [ERROR_CODES.DATABASE.WRITE_FAILED]: '数据保存失败',
  [ERROR_CODES.DATABASE.READ_FAILED]: '数据读取失败',

  [ERROR_CODES.COMMON.INVALID_PARAMS]: '参数无效',
  [ERROR_CODES.COMMON.UNKNOWN]: '发生未知错误',
}

export function getErrorMessage(code: string): string {
  return ERROR_MESSAGES[code] || '发生错误'
}
